name: Deana
favicon: null
layout_spectrum: 0.3953378370497376
typography_spectrum: 0.7606913342606276
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.18992977170273662
  lightness: 0.5777159247081727
  saturation: 0.21787048131227493
  rhythmicContrast: 0.26472310326062143
purpose: []
